---
title: "Curriculum Vitae"
---

```{r setup, include=FALSE,echo=F}
knitr::opts_chunk$set(echo = TRUE)
```

Please find my full CV <a href=Willem_Collier_CV.pdf>here</a>.

### Additional Tidbits

I've always felt I work best when I am a part of a thriving community. Throughout undergraduate and PhD programs, I've worked to keep engaged with and be helpful to my fellow students as well as the Department or research group I work closely with. 

As an undergraduate student, I tutored math and engineering students to not only help with subject material, but also with navigating the program to achieve their broader goals. I have held multiple committee positions throughout my PhD program, including the Graduate Student Advisory Committee, the Equity, Diversity, and Inclusion - Community Engagement Committee, and recently the Faculty Promotion and Retention Committee as the student representative. I also help the Department with student recruitment by attending and talking through my experiences in open houses and meet and greets. I meet frequently with current students to help ease the logistics of difficult processes like the Department's qualifying exam. I am also working to establish a monthly journal club for the biostatistics students in the PHS program. Finally, I believe that being engaged as a researcher requires frequently communicating ongoing research efforts both within and beyond the institution. While I was funded by the Division of Plastic Surgery, I presented on multiple occasions at Division research meetings and at the Department of Surgery's U-INQUIRE research meeting. More recently, I have presented twice to the National Kidney Foundation at the twice-annual CKD-EPI Webinar. As I move forward with my career, I hope to put equal weight on written and oral communication of research. I also hope to do whatever I possibly can to help students and colleagues not only make the most of their research but enjoy it.  

