---
title: "Research"
---

```{r,,include=F,echo=F}
knitr::opts_chunk$set(echo = TRUE)
```

## My Research Journey
I began my time as an undergraduate student in the social sciences. It was through my economics degree that I discovered an enthusiasm for quantitative research methods, and I began taking math courses in my fourth undergraduate year. I deeply enjoyed the math coursework and community, and decided to complete the math degree with emphasis in statistics. While a math student, I did some research in [probability theory](http://www.math.utah.edu/undergraduate/reu-archive.php) (see 2017), but wanted to work on applied problems with potential impact in medicine and health care. Naturally, I gravitated towards biostatistics and chose to continue my education in Utah. I was partially funded by the Division of Plastic Surgery as well as by the Mariner S. Eccles Fellowship during my first two years as a PhD student. I helped Plastic Surgery design, analyze, and write manuscripts for observational surgical outcomes research projects. I was also partially funded by the Study Design and Biostatistics Center (SDBC), where I collaborated with Pediatrics, Orthopedics, and a palliateive care team at the Huntsman Cancer Institute. During years 4 and 5 of my PhD program, I have been funded by the National Kidney Foundation (NKF) to work on research related to the evaluation and application of candidate surrogate endpoints in chronic kidney disease (CKD). I hope to move forward with my career by equally emphasizing statistical methodological research and applied and collaborative research. One of the most exciting aspects of biostatistics is being able to continuously learn more about math and statistics while also developing knowledge about science and medicine through collaboration. 

## Disseration Overview
I have three dissertation projects at various stages (one submitted, second in manuscript preparation, and third in an early-simulation phase). Here is a brief overview of the three projects:

1. We are extending a trial-level Bayesian hierarchical meta-regression approach to surrogate endpoint evaluation to allow variability in the quality of the surrogate across pre-specified subgroups of trials. 
2. A key data input for the trial-level meta-regression evaluation of a surrogate endpoint is commonly treated as a nuisance parameter or is fixed to an arbitrary value because it is difficult to estimate and not often of primary interest. We show mathematically and through a simulation study that this term can drive the interpreted quality of the surrogate by biasing key meta-regression terms, and we provide a Bayesian modeling strategy to handle this term when it is partially missing in available meta-data. 
3. I am working on a sample-size and endpoint adaptive Bayesian clinical trial design for CKD trials, where a combination of multiple surrogate endpoints and/or the established clinical endpoint are used at interim analyses for go/no-go decisions and the choice of final endpoint.

Highlights: Bayesian hierarchical models and meta-regression, surrogate endpoint evaluation, novel adaptive clinical trial design strategies. 

## Other Interests

Much of my early PhD coursework emphasized modern causal inference. I try to emphasize causal theory in the design of the statistical analysis plan in much of my collaborative work, especially when the goal is to estimate the effect of a primary exposure of interest on a clinically relevant outcome. I believe it is critically important to align the study design and statistical analysis with subject expertise such that all members of the study team understand the assumptions necessary to bridge the gap between an association interpretation and a causal one. Ideally, a study should be designed to create potential for a causal conclusion, even if strong causal assumptions cannot be verified. I plan to stay current with my working knowledge of causal theory and methods throughout my career, and I intend to continue to apply causal thinking and methods in collaborative work, where appropriate. 

## Collaborative Publications

### Peer-Reviewed Publications

1. Van Boerum MS, Mann SL, Veith JP, **Collier W**, Hosein RC, Manum JS, Agarwal J, Kwok AC. Patient-reported opioid use for tissue expander-based breast reconstruction. J Plast Reconstr Aesthet Surg. 2021 Apr 18:S1748-6815(21)00218-7. doi: 10.1016/j.bjps.2021.03.114. Epub ahead of print. PMID: 34078588.

2. Veith J, **Collier W**, Simpson A, Magno-Padron D, Mast B, Murphy RX Jr, Agarwal J, Kwok A. A Comparison of Common Plastic Surgery Operations Using the NSQIP and TOPS Databases. Plast Reconstr Surg Glob Open. 2020 May 27;8(5):e2841. doi: 10.1097/GOX.0000000000002841. PMID: 33133901; PMCID: PMC7572021.

3. Magno-Padron DA, **Collier W**, Kim J, Agarwal JP, Kwok AC. A Nationwide Analysis of Early and Late Readmissions following Free Tissue Transfer for Breast Reconstruction. J Reconstr Microsurg. 2020 Jul;36(6):450-457. doi: 10.1055/s-0040-1702175. Epub 2020 Mar 15. PMID: 32172527.

4. Sindt JE, Larsen SD, Dalley AP, **Collier WH**, Brogan SE. The Rate of Infectious Complications After Intrathecal Drug Delivery System Implant for Cancer-Related Pain Is Low Despite Frequent Concurrent Anticancer Treatment or Leukopenia. Anesth Analg. 2020 Jul;131(1):280-287. doi: 10.1213/ANE.0000000000004639. PMID: 31990731.

5. Simpson AM, Kwok AC, **Collier WH**, Kim J, Veith J, Agarwal JP. 2011 ACGME Duty Hour Limits had No Association With Breast Reconstruction Complications. J Surg Res. 2020 Mar;247:469-478. doi: 10.1016/j.jss.2019.09.058. Epub 2019 Oct 23. PMID: 31668433.

6. Veith J, **Collier W**, Rockwell WB, Pannucci C. Direct Comparison of Patient-completed and Physician-completed Caprini Scores for Plastic Surgery Patients. Plast Reconstr Surg Glob Open. 2019 Aug 8;7(8):e2363. doi: 10.1097/GOX.0000000000002363. PMID: 31592033; PMCID: PMC6756651.

7. Mordhorst TR, McCormick ZL, Presson AP, **Collier WH**, Spiker WR. Examining the relationship between epidural steroid injections and patient satisfaction. Spine J. 2020 Feb;20(2):207-212. doi: 10.1016/j.spinee.2019.09.024. Epub 2019 Sep 26. PMID: 31563577.


8. **Collier W**, Scheefer Van Boerum M, Kim J, Kwok AC. Are 30-Day Outcomes Enough? Late Infectious Readmissions following Prosthetic-Based Breast Reconstruction. Plast Reconstr Surg. 2019 Sep;144(3):360e-368e. doi: 10.1097/PRS.0000000000005903. PMID: 31461001.

9. Veith JP, **Collier W**, Kim J, Agarwal J, Kwok A. A national analysis of readmissions for wound healing complications following the repair of lower back, hip, and buttock pressure ulcers using the Nationwide Readmissions Database. Am J Surg. 2019 Apr;217(4):658-663. doi: 10.1016/j.amjsurg.2018.12.013. Epub 2018 Dec 11. PMID: 30638726.





